image: debian/stable
packages:
  - openjdk-11-jdk
  - maven
sources:
  - https://git.sr.ht/~astercrono/java-color-grid
  - https://git.sr.ht/~astercrono/closed-doors
tasks:
  - dependency: |
      cd java-color-grid
      mvn install
  - build: |
      cd closed-doors
      mvn package